title: Andrew Blake | Strategy & AI Scholar
tagline: "Organizational strategy, ecological change, and responsible AI"
url: ""
baseurl: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
collections:
  pages:
    output: true
