title: Dr. Andrew B. Blake
description: Assistant Professor of Strategy and Entrepreneurship 
url: "https://abblake.github.io/"
baseurl: ""

# Personal information
author:
  name: Dr. Andrew Blake
  email: me@andrew-blake.com
  title: Assistant Professor of Strategy and Entrepreneurship
  institution: Texas Tech University
  location: Lubbock, Texas
  bio: "I am an Assistant Professor of Strategy and Entrepreneurship at Texas Tech Univeristy, where I conduct research on dynamic processes through which individual differences and institutional contexts interact to shape strategic choices, drive innovation diffusion, and spark market formation."

# Social links
social:
  twitter: your_twitter
  github: your_github
  linkedin: your_linkedin
  google_scholar: your_scholar_id
  orcid: your_orcid

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock