title: Andrew Blake | Strategy & AI Scholar
tagline: "Organizational strategy, ecological change, and responsible AI"
url: ""
baseurl: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
collections:
  pages:
    output: true
remote_theme: mmistakes/minimal-mistakes
plugins: ["jekyll-include-cache"]   # plus existing plugins
