title: Dr. [Your Name]
description: Assistant Professor & Data Scientist
url: "https://abblake.github.io/"
baseurl: ""

# Personal information
author:
  name: Dr. [Your Name]
  email: your.email@university.edu
  title: Assistant Professor of Data Science
  institution: Your University
  location: City, State
  bio: "I am an Assistant Professor of Data Science at [Your University], where I conduct research at the intersection of artificial intelligence, machine learning, and computational methods. My work focuses on developing novel algorithms that can extract meaningful insights from complex data."

# Social links
social:
  twitter: your_twitter
  github: your_github
  linkedin: your_linkedin
  google_scholar: your_scholar_id
  orcid: your_orcid

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock