title: Dr. Andrew Blake
description: Assistant Professor & Data Scientist
url: "https://abblake.github.io/"
baseurl: ""

# Personal information
author:
  name: Dr. Andrew Blake
  email: your.email@university.edu
  title: Assistant Professor of Strategic Management
  institution: Your University
  location: City, State
  
# Social links
social:
  twitter: your_twitter
  github: your_github
  linkedin: your_linkedin
  google_scholar: your_scholar_id
  orcid: your_orcid

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock